name: build_windows

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        os: [ windows-latest ]
    steps:
      - name: Download Wix
        uses: i3h/download-release-asset@v1
        with:
          owner: wixtoolset
          repo: wix3
          tag: wix3141rtm
          file: wix314-binaries.zip
      - name: Decompress Wix
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: wix314-binaries.zip
          pathTarget: ./target/wix
      - name: Add Wix to Path
        run: echo "$HOME/target/wix" >> $GITHUB_PATH
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: liberica
          java-package: jdk+fx
          cache: maven
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml -Pwindows-active,windows-msi
      - name: Zip the AppImage
        run: Compress-Archive -Path target/app-image/DevTool -Destination target/DevTool-${{ github.ref_name }}-${{ matrix.os }}.zip
      - name: Update Automatic Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ matrix.os }}
          prerelease: false
          title: DevTool-${{ github.ref_name }}-${{ matrix.os }}
          files: |
            ./target/*.zip
            ./target/*.msi
